default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: docker_rails_development
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: be_test

production:
  <<: *default
  database: be_production
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>
